name: Build unsigned IPA
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Generate Xcode project
        run: xcodegen generate

      - name: Archive (unsigned)
        run: |
          set -euo pipefail
          xcodebuild \
            -project InfiniteBlues.xcodeproj \
            -scheme InfiniteBlues \
            -configuration Release \
            -archivePath "$RUNNER_TEMP/InfiniteBlues.xcarchive" \
            -destination 'generic/platform=iOS' \
            CODE_SIGNING_ALLOWED=NO \
            clean archive

      - name: Package .ipa (unsigned)
        run: |
          set -euo pipefail
          APP_PATH="$RUNNER_TEMP/InfiniteBlues.xcarchive/Products/Applications/InfiniteBlues.app"
          mkdir -p Payload
          cp -R "$APP_PATH" Payload/
          zip -qry InfiniteBlues-unsigned.ipa Payload

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: InfiniteBlues-unsigned-ipa
          path: InfiniteBlues-unsigned.ipa
          if-no-files-found: error
